import Head from 'next/head'
import Image from 'next/image'
import Categories from '../components/Categories'
import PostCard from '../components/PostCard'
import PostWidget from '../components/PostWidget'
import {GET_POST} from "../graphgql"




export default function Home({ posts }) {
  // const posts = [
  //   {
  //     title: "react 1",
  //     excerpt: "learn react sg sgf fgd hff gh fd hf hfghfdh fdh fdg hfh dfgh fdgh fgd hdhdf ghdfh dfh",
  //     slug: "reactdev1",
  //     img: "/image/example1.png",
  //     auther: "James Brook",
  //     date: "17 January 2019"
  //   },
  //   {
  //     title: "react 2",
  //     excerpt: "learn react fgdhesh sdgh dg hgfdj hd ncfhryhgcx sgh gh xhgfxh x hgxdhs hdfxthgxh ",
  //     slug: "reactdev2",
  //     img: "/image/example2.png",
  //     auther: "James Brook",
  //     date: "20 January 2019"
  //   }
  // ]

  return (
    <div className='container mx-auto px-10 mb-8 '>
      <Head>
        <title>New2morrow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 '>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget/>
            <Categories posts={posts}/>
          </div>
        </div>
      </div>


    </div>
  )
}


export async function getStaticProps() {
  const posts = (await GET_POST()) || []

  return {
    props: { posts }
  }
}