import Head from 'next/head'
import Image from 'next/image'
import Categories from '../components/Categories'
import PostCard from '../components/PostCard'
import PostWidget from '../components/PostWidget'
import { GET_POST } from "../graphgql"
import FeaturedPosts from "../sections/FeaturedPost"




export default function Home({ posts }) {


  return (
    <div className='container mx-auto px-10 mb-8 '>
      <Head>
        <title>New2morrow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <FeaturedPosts /> */}
      
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 '>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories posts={posts} />
          </div>
        </div>
      </div>


    </div>
  )
}


export async function getStaticProps() {
  const posts = (await GET_POST()) || []

  return {
    props: { posts }
  }
}